### ISSUE TITLE
Feature request: use premake to build the projects

### ISSUE THREAD

**Issue by Halmaethor** [mdparker/Derelict3#1]
You could use premake-dev-d from bitbucket, either from [Goughy](https://bitbucket.org/goughy/premake-dev-d) or [mine](https://bitbucket.org/hellknight/premake-dev-d). 

**Pros:**
- The premake executable has a really small footprint, so you can put it into the repository.
- The premake configuration files are easy to create and read.

**Cons:**
- You need to learn a bit of Lua? (not really sure if it should be considered a cons...)
- It currently only creates makefiles, but I'm planning to support the creation of Sublime Text projects and Visual Studio solutions.

**Comment by mdparker** [comment]
I'm quite familiar with Premake4. I use it frequently with my C projects. I also toyed around with premake-dev-d when it was mentioned in the newsgroup. But, I'm hesitant to make use of it here. The thing is, Derelict is dead simple to build and has no dependencies. The simple D script I have now isn't much more complex than a premake script and has the further benefit that it works (or will eventually) with whatever compiler the user has installed without any need to add any binaries to the repo. I think Premake is fine for complex projects, but for Derelict I just don't see a need. 

Still, I'll leave this open and consider it.
