### ISSUE TITLE
glDeleteFramebuffers binds to glBindBufferRange

### ISSUE THREAD

**Issue by jackun** [mdparker/Derelict3#106]
Copy/paste error
https://github.com/aldacron/Derelict3/blob/master/import/derelict/opengl3/arb.d#L1020

Proper link? https://github.com/aldacron/Derelict3/blob/efd908127fc66a7b3ce415572b505dc1f1109bbd/import/derelict/opengl3/arb.d#L1020

**Comment by jackun** [comment]
Ok, i'm gonna make this overall copy/paste error issue and glutter up this space.
2.) something going on at glPopAttrib  https://github.com/aldacron/Derelict3/blob/master/import/derelict/opengl3/deprecatedFunctions.d#L216

3.) glPopAttrib bind also missing https://github.com/aldacron/Derelict3/blob/master/import/derelict/opengl3/gl.d#L358

Maybe should just fork this :P

**Comment by mdparker** [comment]
OK, just fixed these via github's online editor. Hope it didn't mess anything up. I should be able to make sure it compiles later tonight once I get my post-format dev environment set up. Thanks for this!
