### ISSUE TITLE
 luaL_newlibtable nrec value

### ISSUE THREAD

**Issue by John-Colvin** [mdparker/Derelict3#109]
lua/macros.d: L111

void luaL_newlibtable(lua_State\* L, luaL_Reg\* l) {
    lua_createtable(L, 0, l.sizeof / l[0].sizeof - 1);
}

on x86_64:

l.sizeof == 8
l[0].sizeof == 16
l.sizeof / l[0].sizeof == 0 //integer division
l.sizeof / l[0].sizeof - 1 == ulong.max

I'm no Lua expert, but i'm pretty sure that's not the value we want to pass, especially to a function that expects an int.

**Comment by mdparker** [comment]
Thanks! We may get this binding into good shape before too much longer. I've been tempted just to go in and redo the whole thing myself. Are you currently using it in a project?

**Comment by mdparker** [comment]
OK, I've dug around in the Lua headers to see what's going on. I think I've got a handle on it. I changed a couple of function signatures to take luaL_Reg[] instead of luaL_Reg*, since that's what the C macros appear to expect anyway. Also fixed a similar issue in lua_pushliteral a few lines above.
