### ISSUE TITLE
Maximum GLVersion detection incorrect.

### ISSUE THREAD

**Issue by RoseQuix** [mdparker/Derelict3#110]
The detection logic used by DerelictGL3 when finding the maximum GL version is flawed and will in some cases detect an incorrect version due to the driver version containing a GL version number within it. As an example from my Macbook:

3.2 NVIDIA-8.10.44 304.10.65f03

Is the result given by glGetString(GL_VERSION). Derelict's max version logic sees the 4.1 in 304.10.65f03 and assumes OpenGL 4.1 is supported. This, naturally, causes errors when attempting to reload the symbols.

The logic for detecting the maximum version either needs reworking, or Derelict needs to support a slightly more graceful failure to load beyond the detected maximum version. Perhaps a failure ceases to load the failed GL version and beyond? Another alternative seems to be the version string always begins with the GL version (but I am unable to verify this).

I also submitted a pull request with a fix I put together, I hope I did this correctly, I've never done this before.

**Comment by mdparker** [comment]
"Perhaps a failure ceases to load the failed GL version and beyond? "

That is supposed to be the behavior already. I'll look into this as soon as I have a chance.

**Comment by RoseQuix** [comment]
Looking at it again, it does seem that it will successfully have loaded earlier versions if you try/catch the reload call, but since it leaves reload, the loadedVersion property never gets updated so it loads every version it can until failure, but still thinks it only loaded up to version 1.1

**Comment by mdparker** [comment]
I see what you mean. I've wrapped the saving off of the loaded version in a scope(exit), so that coupled with your pull request should fix this stuff once and for all. Thanks!
