### ISSUE TITLE
LUA lib

### ISSUE THREAD

**Issue by bioinfornatics** [mdparker/Derelict3#115]
I do not see anymore the lua binding lib?

with linux OS and build as shared lib

**Comment by mdparker** [comment]
It's all still there. The repository was temporarily in a disrupted state because of a bad merge, but I reverted the merge shortly after. You must have pulled while it was messed up. Try updating your working copy again and it should all be well.

**Comment by bioinfornatics** [comment]
From rev d8aa11d i do not found libDerelictLUA.so.3.0.0

```
$ ls ../../BUILD/derelict-20130516gitd8aa11d/lib/
libDerelictAL.so.3.0.0      libDerelictFG.so.3.0.0  libDerelictGL3.so.3.0.0    libDerelictODE.so.3.0.0  libDerelictSDL2.so.3.0.0   libDerelictUtil.so.3.0.0
libDerelictAL.so.3.0.o      libDerelictFG.so.3.0.o  libDerelictGL3.so.3.0.o    libDerelictODE.so.3.0.o  libDerelictSDL2.so.3.0.o   libDerelictUtil.so.3.0.o
libDerelictALURE.so.3.0.0   libDerelictFI.so.3.0.0  libDerelictGLFW3.so.3.0.0  libDerelictOGG.so.3.0.0  libDerelictSFML2.so.3.0.0
libDerelictALURE.so.3.0.o   libDerelictFI.so.3.0.o  libDerelictGLFW3.so.3.0.o  libDerelictOGG.so.3.0.o  libDerelictSFML2.so.3.0.o
libDerelictASSIMP.so.3.0.0  libDerelictFT.so.3.0.0  libDerelictIL.so.3.0.0     libDerelictPQ.so.3.0.0   libDerelictTCOD.so.3.0.0
libDerelictASSIMP.so.3.0.o  libDerelictFT.so.3.0.o  libDerelictIL.so.3.0.o     libDerelictPQ.so.3.0.o   libDerelictTCOD.so.3.0.o
```

**Comment by bioinfornatics** [comment]
```
../import/derelict/lua/macros.d(112): Error: function pointer lua_createtable (lua_State* L, int fromidx, int toidx) is not callable using argument types (lua_State*,int,ulong)
```

line 90 lua/functions.d third parameter should to be a `size_t` maybe

**Comment by mdparker** [comment]
No, I can't change it to size_t because the C library expects an int. In this particular case, it should be safe enough to cast to an int in lua_newlibtable. I've updated the repo to do so. Let me know if this solves the issue for you.

**Comment by mdparker** [comment]
Since I haven't heard anything else, I'll assume this is good to go now.

**Comment by bioinfornatics** [comment]
yes is good thanks
