### ISSUE TITLE
SDL2.dll broken link 

### ISSUE THREAD

**Issue by maser111** [mdparker/Derelict3#120]
Hi, the link to the SDL2.dll in the download section in the README.markdown is broken.

Can you also put a link to the SDL2.lib?

Thanks :)

**Comment by mdparker** [comment]
The link is working for me. And you don't need SDL2.lib to use DerelictSDL2.

**Comment by maser111** [comment]
I'm so sorry... was a strange behaviour of my antivirus blocking the download... :(

**Comment by mdparker** [comment]
No worries!
