### ISSUE TITLE
rdmd build fails

### ISSUE THREAD

**Issue by denizzzka** [mdparker/Derelict3#124]
$ git clone git@github.com:aldacron/Derelict3.git
Cloning into Derelict3...
X11 forwarding request failed on channel 0
remote: Counting objects: 1777, done.
remote: Compressing objects: 100% (862/862), done.
remote: Total 1777 (delta 760), reused 1660 (delta 659)
Receiving objects: 100% (1777/1777), 642.36 KiB | 184 KiB/s, done.
Resolving deltas: 100% (760/760), done.
$ cd Derelict3/build/
$ rdmd build.d
Using the Digital Mars DMD compiler.
Using the Digital Mars DMD compiler.
Building all packages.
Building DerelictPQ
## std.file.FileException@std/file.d(2394): /tmp/.rdmd-1000/rdmd-build.d-1153E3FFF76CA6CE090CC23FC25418A4/../import/derelict/pq/: No such file or directory

/tmp/.rdmd-1000/rdmd-build.d-1153E3FFF76CA6CE090CC23FC25418A4/build(bool std.file.DirIteratorImpl.stepIn(immutable(char)[])+0x61) [0x484a35]
/tmp/.rdmd-1000/rdmd-build.d-1153E3FFF76CA6CE090CC23FC25418A4/build(ref std.file.DirIteratorImpl std.file.DirIteratorImpl.__ctor(immutable(char)[], std.file.SpanMode, bool)+0x9d) [0x484d51]
/tmp/.rdmd-1000/rdmd-build.d-1153E3FFF76CA6CE090CC23FC25418A4/build(std.file.DirIteratorImpl\* std.conv.emplace!(std.file.DirIteratorImpl, immutable(char)[], std.file.SpanMode, bool).emplace(std.file.DirIteratorImpl_, ref immutable(char)[], ref std.file.SpanMode, ref bool)+0x48) [0x47c130]
/tmp/.rdmd-1000/rdmd-build.d-1153E3FFF76CA6CE090CC23FC25418A4/build(void std.typecons.__T10RefCountedTS3std4file15DirIteratorImplVE3std8typecons24RefCountedAutoInitialize0Z.RefCounted.RefCountedStore.initialize!(immutable(char)[], std.file.SpanMode, bool).initialize(ref immutable(char)[], ref std.file.SpanMode, ref bool)+0x83) [0x472e6f]
/tmp/.rdmd-1000/rdmd-build.d-1153E3FFF76CA6CE090CC23FC25418A4/build(ref std.typecons.__T10RefCountedTS3std4file15DirIteratorImplVE3std8typecons24RefCountedAutoInitialize0Z.RefCounted std.typecons.__T10RefCountedTS3std4file15DirIteratorImplVE3std8typecons24RefCountedAutoInitialize0Z.RefCounted.__ctor!(immutable(char)[], std.file.SpanMode, bool).__ctor(ref immutable(char)[], ref std.file.SpanMode, ref bool)+0x11) [0x472de1]
/tmp/.rdmd-1000/rdmd-build.d-1153E3FFF76CA6CE090CC23FC25418A4/build(ref std.file.DirIterator std.file.DirIterator.__ctor(immutable(char)[], std.file.SpanMode, bool)+0x40) [0x46fd24]
/tmp/.rdmd-1000/rdmd-build.d-1153E3FFF76CA6CE090CC23FC25418A4/build(std.file.DirIterator std.file.dirEntries(immutable(char)[], std.file.SpanMode, bool)+0x39) [0x470175]
/tmp/.rdmd-1000/rdmd-build.d-1153E3FFF76CA6CE090CC23FC25418A4/build(void derelict.buildPackage(immutable(char)[])+0x12a) [0x457f0a]
/tmp/.rdmd-1000/rdmd-build.d-1153E3FFF76CA6CE090CC23FC25418A4/build(void derelict.buildAll()+0x8e) [0x457c06]
/tmp/.rdmd-1000/rdmd-build.d-1153E3FFF76CA6CE090CC23FC25418A4/build(_Dmain+0x2da) [0x457b3a]
/tmp/.rdmd-1000/rdmd-build.d-1153E3FFF76CA6CE090CC23FC25418A4/build(extern (C) int rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).void runMain()+0x18) [0x46b978]
/tmp/.rdmd-1000/rdmd-build.d-1153E3FFF76CA6CE090CC23FC25418A4/build(extern (C) int rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).void tryExec(scope void delegate())+0x2a) [0x46b4aa]
/tmp/.rdmd-1000/rdmd-build.d-1153E3FFF76CA6CE090CC23FC25418A4/build(extern (C) int rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])_).void runAll()+0x40) [0x46b9c8]
/tmp/.rdmd-1000/rdmd-build.d-1153E3FFF76CA6CE090CC23FC25418A4/build(extern (C) int rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).void tryExec(scope void delegate())+0x2a) [0x46b4aa]
/tmp/.rdmd-1000/rdmd-build.d-1153E3FFF76CA6CE090CC23FC25418A4/build(_d_run_main+0x1ae) [0x46b466]
/tmp/.rdmd-1000/rdmd-build.d-1153E3FFF76CA6CE090CC23FC25418A4/build(main+0x17) [0x46b2b3]

**Comment by mdparker** [comment]
Don't use rdmd for this. Compile build.d with DMD/LDC/GDC directly. It only need be done once each time its updated.

dmd build.d
build

**Comment by denizzzka** [comment]
ok
then it is necessary to fix readme
