### ISSUE TITLE
glFramebufferParameteri

### ISSUE THREAD

**Issue by Dav1dde** [mdparker/Derelict3#125]
`glFramebufferParameteri` seems to be missing

**Comment by mdparker** [comment]
Nope. It's there: https://github.com/aldacron/Derelict3/blob/master/import/derelict/opengl3/arb.d#L2718

What sort of error are you seeing?

**Comment by Dav1dde** [comment]
Interesting, when I try to import that function dmd says it does not exist. I can give you the exact error later. Used here [https://github.com/Dav1dde/glamour/blob/master/glamour/fbo.d](https://github.com/Dav1dde/glamour/blob/master/glamour/fbo.d)

**Comment by mdparker** [comment]
I'm going to go ahead and close this, since the function isn't actually missing. If you do discover a bug with Derelict in this, please open a new issue for it. Thanks!
