### ISSUE TITLE
GLFWkeyfun should have 4 int parameters, not 3

### ISSUE THREAD

**Issue by Ka-lua** [mdparker/Derelict3#130]
In glfw3.types, GLFWkeyfun is declared as

alias void function(GLFWwindow*, int, int, int) GLFWkeyfun;

but its correct signature is

alias void function(GLFWwindow*, int key, int scancode, int action, int mods) GLFWkeyfun;

For reference, see http://www.glfw.org/docs/3.0/group__input.html#ga592dd1919f8a1dc7576b13cdd8b7b695

**Comment by mdparker** [comment]
Ah, that scancode param is a recent addition. I'm glad 3.0 was finally released. I don't have to track so many changes anymore. But I won't be surprised if I overlooked something else. Thanks!
