### ISSUE TITLE
No links to documentation or examples

### ISSUE THREAD

**Issue by hdon** [mdparker/Derelict3#135]
I think it would be great if the readme contained links to documentation and examples projects that are intended to build with recent revisions of Derelict, and maybe even say which revisions they've been tested with.

**Comment by mdparker** [comment]
I'll eventually get a bit of documentation up on the wiki, including examples. Derelict really isn't that complicated. The only thing specific to the library that you generally have to know is DerelictFoo.load() (DerelictGL3 being the exception). So I don't think it really matters which revisions people compile against. Anyway, documentation is on the todo list. I just need the time and motivation to get to it. Actually, it's the one thing preventing me from taking the 'Alpha' bit out of the readme.
