### ISSUE TITLE
License blurb on build.d? 

### ISSUE THREAD

**Issue by aubade** [mdparker/Derelict3#136]
Sorry for being over-pedantic, but I'd like to swipe build.d and modify it to work with another project, but it doesn't seem to have any license info at the top of the file, and I couldn't find a project-wide license file that would apply by default.

I'm guessing it's intended to be under the boost license like the rest of the project, but if it's not too much trouble, could I get that made explicit?

**Comment by mdparker** [comment]
Never even considered that before. Done!
