### ISSUE TITLE
lua_Debug struct Forward reference in Lua Binding

### ISSUE THREAD

**Issue by serates** [mdparker/Derelict3#145]
In the DerelictLua binding in types.d the lua_Debug struct is defined without a body leading it to be a forward reference. This leads to issues when using the binding. Replacing struct lua_Debug; with the following fixes this issue:

```
struct lua_Debug {
   int event;
   const char *name;
   const char *namewhat;
   const char *what;
   const char *source;
   int currentline;
   int nups;
   int linedefined;
   int lastlinedefined;
   char[] short_src;
   int i_ci;
}
```

**Comment by mdparker** [comment]
No, this isn't a bug. If you look in lua.h, you will find this:

``` C
typedef struct lua_Debug lua_Debug;
```

It's an opaque struct and you are not intended to access its fields. It is used in the public API only through pointers. Don't declare instances of lua_Debug, only pointers, and you won't have the problem.

There is a bug in DMD right now that prevents arrays of opaque struct pointers from being declared, so if that's where you're getting the forward reference errors you'll have to work around it in a different way.
