### ISSUE TITLE
SDL_SetMainReady not found in libSDL2.so (RC 1.1, in Ubuntu repos)

### ISSUE THREAD

**Issue by soltanmm** [mdparker/Derelict3#153]
My copy of libSDL2.so (From the Ubuntu 13.10 dev preview repos, RC 1.1) does not contain the function 'SDL_SetMainReady' (see symbol dump here: http://pastebin.com/XbeUmFU2), and therefore the loader errors out. That said, upon catching the error and ignoring it, I can use SDL2 to successfully create a window and clean up and stuff without a hitch (the reported 'bad stuff happening' in the code comments has yet to occur to me). Admittedly valgrind reports memory leaks at exit, but I think that's something more endemic to D programming in general at the moment. >_<

Annndddd, the obligatory-statement-of-repo-newcomers-BUT-IT'S-STILL-TRUE: Thanks for this awesome wrapper lib!

**Comment by mdparker** [comment]
One of the annoyances of dealing with libraries that want to wrap main. I've always believed that this sort of thing doesn't belong in a library. But, nothing I can do it about it! I've modified the loader so that no exception is thrown if it fails to load. Thanks!
