### ISSUE TITLE
Opaque structures in SDL2 bindings

### ISSUE THREAD

**Issue by NCrashed** [mdparker/Derelict3#155]
Platform: Fedora 18 x86_64
Compiler: DMD64 D Compiler v2.063.2

I have some problems with opaque structures in my Irrlicht binary port. 
Sample code:

```
Window = cast(SDL_Window*)param.WindowId;
```

Will cause such errors:

```
../../.dub/packages/derelict-master/import/derelict/sdl2/types.d(2033): Error: struct derelict.sdl2.types.SDL_Window unknown size
../../.dub/packages/derelict-master/import/derelict/sdl2/types.d(2033): Error: struct derelict.sdl2.types.SDL_Window no size yet for forward reference
```

Also i cannot create array of pointers to opaque structures:

```
SDL_Joystick*[] Joysticks = [];
```

Will cuase:

```
../../.dub/packages/derelict-master/import/derelict/sdl2/types.d(796): Error: struct derelict.sdl2.types.SDL_Joystick is forward referenced when looking for 'toHash'
../../.dub/packages/derelict-master/import/derelict/sdl2/types.d(796): Error: struct derelict.sdl2.types.SDL_Joystick is forward referenced when looking for 'opCmp'
../../.dub/packages/derelict-master/import/derelict/sdl2/types.d(796): Error: struct derelict.sdl2.types.SDL_Joystick is forward referenced when looking for 'toString'
../../.dub/packages/derelict-master/import/derelict/sdl2/types.d(796): Error: struct derelict.sdl2.types.SDL_Joystick unknown size
../../.dub/packages/derelict-master/import/derelict/sdl2/types.d(796): Error: struct derelict.sdl2.types.SDL_Joystick no size yet for forward reference
../../.dub/packages/derelict-master/import/derelict/sdl2/types.d(796): Error: struct derelict.sdl2.types.SDL_Joystick unknown size
../../.dub/packages/derelict-master/import/derelict/sdl2/types.d(796): Error: struct derelict.sdl2.types.SDL_Joystick no size yet for forward reference
```

But if i change declaration for problem structs, all compiles fine:

```
\\Before
struct SDL_Window;
\\After
struct SDL_Window {}
```

Should declarations be changed in such manner? This fix doesn't break existing code and doesn't change usage semantics.

**Comment by mdparker** [comment]
1) (the cast error) Never seen that one before. The best thing to do is try to create a minimal code sample that demonstrates the error and post a bug report on the DMD bug tracker. Personally, I'd like to see more of your code. Is there a github repo I can look at?

2) (Arrays) That is a known issue and is already in the DMD bug tracker. See http://d.puremagic.com/issues/show_bug.cgi?id=10451

3) Should they change? No, they shouldn't, as that's not a fix. It's a workaround, and one with side effects (it adds a TypeInfo for each struct type declared that way). The way they are implemented now is correct.

Another bug I submitted back in January about opaque structs was just fixed the other day, so it may take a while for the array issue to be fixed. You might want to vote for the array bug. I don't know if anyone pays attention to the votes anymore, but it can't hurt.

**Comment by mdparker** [comment]
Actually, regarding the arrays, I was only seeing problems when the array is declared as a struct field. In classes and outside of structs, it disappears. But since you are initializing your array to [](not sure why you'd do that), I decided to do a quick test with that. With the initialization, I see the errors. Without, they go away. So provided your array isn't in a struct, that's the solution to this particular problem. I'll update my bug report with that info.

**Comment by mdparker** [comment]
OK, I found your DIrrlicht repo and worked out a test case. The problem is casting from void\* to opaqueStruct*. I've submitted a bug report.

http://d.puremagic.com/issues/show_bug.cgi?id=10793

**Comment by NCrashed** [comment]
Thanks for all-embracing answer. I voted for the cast bug and will use workaround for arrays. I hope this bug will be fixed soon.

**Comment by mdparker** [comment]
Oh, the markup ate my brackets in my post. Your workaround is this:

``` D
// Instead of this
SDL_Joystick*[] Joysticks = [];

// Do this
SDL_Joystick*[] Joysticks;
```

**Comment by NCrashed** [comment]
But creating array in constructor, for instance, invokes same error.

```
SDL_Joystick*[] Joysticks;

//class constructor
this()
{
   Joysticks = new (SDL_Joystick*)[0];
}
```

**Comment by mdparker** [comment]
You don't need to allocate an empty dynamic array. Just by declaring it,
you already have an array of length 0. What you are doing is creating an
empty array, then assigning an empty array to it. Redundant.
