### ISSUE TITLE
assimp3: add defines and enum from config.h

### ISSUE THREAD

**Issue by vuaru** [mdparker/Derelict3#167]
Assimp3 (and assimp?) is missing the defines and enum from config.h, needed for setting import properties. (http://assimp.sourceforge.net/lib_html/config_8h.html)

**Comment by mdparker** [comment]
I'll get to this later this week. Got a lot going on right now. In the meantime, you can just pass the values directly. Or declare the ones you need.

**Comment by mdparker** [comment]
This is now in the repo. Sorry for taking so long.
