### ISSUE TITLE
Discrepancy between dub registry and package.json

### ISSUE THREAD

**Issue by p0nce** [mdparker/Derelict3#168]
http://code.dlang.org/packages/derelict

vs

https://github.com/aldacron/Derelict3/blob/master/package.json

It affects users of gfm which depends on DerelictAssimp3.

Might be a dub registry problem because I thought package.json was pulled regularly.
You may force a package content update throught remove/add in dub registry web interface.

**Comment by p0nce** [comment]
Actually, not a real problem

**Comment by simendsjo** [comment]
I don't see how this is not a problem. Add gfm as a dependency and run `dub`. The package `derelict` uses Derelict3, and all `derelict:lib packages`. The other packages are `derelict-lib`.
Trying to change `gfm` dependencies to `derelict-lib` didn't work very well. I had to use `dub install` on each of them, but it still couldn't find them. Installing derelict first actually works. Could this be a dub issue?

**Comment by p0nce** [comment]
Do you still have a problem now that gfm is dependent upon DerelictOrg? (EDIT: discard this comment, see below)

**Comment by p0nce** [comment]
I can reproduce a similar problem! Removing all packages and locally added package.json. 

```
 Error: Unknown dependency: derelict-sdl2
```

(despite derelict-sdl2 existing on the registry and being rightly packaged)
It seems dependencies are not found when required by a subpackage or something.

Two workarounds exactly like you said: 
- putting the dependency directly in the app package.json
- installing the dependency manually

So it seems like a dub problem.
