### ISSUE TITLE
ETA on Derelict-SFML in DerelictOrg repo?

### ISSUE THREAD

**Issue by TyOverby** [mdparker/Derelict3#169]
I'm going to make a game in D using SFML and I'd like to use the Derelict port.  Should I use the Derelict3/SFML port or wait until it shows up in DUB under derelict-SFML?

I don't mean to be pushy, but an ETA would help me out a lot!

Thanks for the work that you do,
-- TyOverby

**Comment by mdparker** [comment]
Sorry, can't really give an ETA. I get to this stuff when I can find the time. The next package to go, which is way over due, will be the AssImp3 binding. I'll get to SFML after that. In the meantime, go ahead and use Derelict 3. As long as you are using dub to manage your project, changing over to the DerelictOrg packages will be as simple as editing your dependencies.

Also, please ask questions like this over at the Derelict forums in the future. The issues list here should be strictly for bug reports and enhancement requests. Thanks!

**Comment by mdparker** [comment]
FYI, DerelictSFML2 is ~~not~~ now part of DerelictOrg, so you should be able to switch over to using derelict-sfml2 in your dub dependencies once the registry updates.
