### ISSUE TITLE
Segmentation Fault when calling IMG_LoadTexture

### ISSUE THREAD

**Issue by wswright** [mdparker/Derelict3#170]
The following lines cause a segmentation fault:
SDL_Texture *loadedImage;
loadedImage = IMG_LoadTexture(ren, toStringz(fileName));
- ren is my renderer
- filename is a valid path to a bmp image (it loads w/ SDL_LoadImage)

My package.json dependencies:
"dependencies": {
    "derelict-sdl2" : "~master"
}

**Comment by mdparker** [comment]
Did you call DerelictSDL2Image.load followed by IMG_Init?

In future, please bring this kind of problem to the Derelict forums at http://dblog.aldacron.net/forum/index.php. The Issue tracker is for bug reports and enhancement requests. Thanks.
