### ISSUE TITLE
SDL_WindowFlags: SDL_WINDOW_ALLOW_HIGHDPI is missing

### ISSUE THREAD

**Issue by Dgame** [mdparker/Derelict3#171]
Here:
http://hg.libsdl.org/SDL/file/default/include/SDL_video.h#l111
But not here:
https://github.com/aldacron/Derelict3/blob/master/import/derelict/sdl2/types.d#L2036

:)

**Comment by mdparker** [comment]
I haven't updated to SDL 2.01 yet. I'll get around to it soon.

**Comment by Dgame** [comment]
Would be kind if you could confirm this here, so I will be informed. Thank you. :)

**Comment by mdparker** [comment]
OK, I've updated to SDL 2.0.1. Please be aware that this means the 2.0.0 shared library will fail to load now.

**Comment by Dgame** [comment]
You've ruined it. :(

**Comment by mdparker** [comment]
What do you mean?

**Comment by Dgame** [comment]
Someone cheered too soon. The fault seems to lie somewhere in me. You have again been lucky. ;)

**Comment by Dgame** [comment]
Could it be that you have forgotten to bind SDL_GL_GetCurrentWindow and SDL_GL_GetCurrentContext?

**Comment by mdparker** [comment]
Ugh. I declared the aliases but overlooked the rest. The DerelictOrg repo is correct though. Fixed now. Thanks!
