### ISSUE TITLE
SDL_MessageBoxButtonData: buttonid is erroneously an int and not an int*

### ISSUE THREAD

**Issue by Dgame** [mdparker/Derelict3#172]
https://github.com/aldacron/Derelict3/blob/master/import/derelict/sdl2/functions.d#L256

http://hg.libsdl.org/SDL/file/ba26f042e36d/include/SDL_messagebox.h#l119

edit:
corrected wrong link

**Comment by mdparker** [comment]
Fixed. Thanks!
