### ISSUE TITLE
alureDestroyStream

### ISSUE THREAD

**Issue by mbj2011** [mdparker/Derelict3#176]
has the following signature;
<code>
ALboolean function(alureStream_, ALsizei, ALsizei, ALuint_) 
</code>
in derelict/alure/functions.

According to the ALURE docs (http://kcat.strangesoft.net/alure-docs/files/stream-cpp.html#alureDestroyStream), it is supposed to look like this:
<code>
ALURE_API ALboolean ALURE_APIENTRY alureDestroyStream(alureStream\* stream, ALsizei numBufs, ALuint\* bufs)
</code>

Is this a mistake or am I missing something?

**Comment by mdparker** [comment]
It's a mistake. I've just pushed the fix. Thanks!

**Comment by mdparker** [comment]
Oh, sorry. I pushed the fix to DerelictOrg, not here. Didn't realize this was the Derelict 3 repo. Can you not switch to DerelictOrg? My intention is to no longer maintain Derelict 3. I'll put this one in, though, since I haven't updated the README yet.

**Comment by mbj2011** [comment]
Thanks!
I wasn't even aware of DerelictOrg! I'll make the switch right away...
You might want to update http://www.dsource.org/projects/derelict. :)

**Comment by mdparker** [comment]
Yeah, I just updated the README after I pushed the fix here. I had announced it on my blog and put off the README update for later, then it slipped my mind.
