### ISSUE TITLE
ManyMouse

### ISSUE THREAD

**Issue by jcdickinson** [mdparker/Derelict3#180]
I would normally do a PR for this, but with submodules etc. I'm not too sure how that would work.

I have wrapped [ManyMouse](https://icculus.org/manymouse/) (Windows/Linux/Mac raw/multiple mouse input). Feel free to add it to Derelict if you wish.

https://gist.github.com/jcdickinson/d6ca06a19e1a7e38c78e

The only issue is that ManyMouse has no shared library release, so I went for the most logical names for it. I have tested it with a ManyMouse DLL I built locally.

**Comment by mdparker** [comment]
Interesting. Small API which won't be difficult to maintain. Plus, I'm familiar with Ryan's work on other projects, so that's a plus. If I do add it, it will be to DerelictOrg and not here :) Thanks!
