### ISSUE TITLE
errors compiling with dmd 2.060

### ISSUE THREAD

**Issue by jordisayol** [mdparker/Derelict3#22]
I'm getting this errors when compiling with dmd 2.060 beta:

```
[...]
../import/derelict/opengl3/glx.d(177): Error: expected 3 function arguments, not 2
../import/derelict/opengl3/glx.d(178): Error: expected 3 function arguments, not 2
[...]
../import/derelict/opengl3/glx.d(198): Error: expected 3 function arguments, not 2
[...]
Building DerelictSFML2

std.file.FileException@std/file.d(2514): ../import/derelict/sfml2/: No such file or directory
[...]
```

**Comment by mdparker** [comment]
OK, the last error is easy. I'm working on a package for SFML2 and accidentally committed the local build script changes I'd made to compile it. As for the rest, it seems you've found a bug in the beta compiler, in that it's ignoring default arguments.

**Comment by jordisayol** [comment]
Is it possible to create a reduced test case to report in bugzilla? I'm not able to do that.
BTW, dmd 2.060 will be released next saturday.

**Comment by mdparker** [comment]
Hmm. On the beta mailing list, I saw the thread where Walter mentioned that it was time for a new beta, but I've not yet seen any links. Where did you download it?

**Comment by jordisayol** [comment]
I download last commit from https://github.com/D-Programming-Language , and compiled it

**Comment by mdparker** [comment]
I'll just wait for the beta to be released. Should be soon.

**Comment by jordisayol** [comment]
commit 3971f4002cb8784b4553e578dce5a6444320be90 removes compilation errors with latest dmd from git-master.
Thanks!

**Comment by mdparker** [comment]
Oh, thanks for closing this. I forgot about it.
