### ISSUE TITLE
glGenVertexArrays and associated functions not bound in Derelict

### ISSUE THREAD

**Issue by brendanzab** [mdparker/Derelict3#30]
Is there any reason why `glGenVertexArrays(GLsizei n,  GLuint *arrays)`, `glBindVertexArray(GLuint array)` and `glDeleteVertexArrays(GLsizei n,  GLuint *arrays)` are absent from `opengl3/functions.d`? Reading around, it seems as if VAOs are _required_ in programs using the OpenGL 3.2 Core Profile and up. These functions are defined in the OS X version of `gl3.h` and also in the GL3 man pages:
- [glGenVertexArrays](http://www.opengl.org/sdk/docs/man3/xhtml/glGenVertexArrays.xml)
- [glBindVertexArray](http://www.opengl.org/sdk/docs/man3/xhtml/glBindVertexArray.xml)
- [glDeleteVertexArrays](http://www.opengl.org/sdk/docs/man3/xhtml/glDeleteVertexArrays.xml)

Just seeking clarification (as usual, I have no idea what I'm doing, haha). If this was indeed unintentional, I can quickly do the work and submit a pull request.

**Comment by brendanzab** [comment]
Ahh, I see. They're defined in `opengl3/arb.d`. My bad!

**Comment by mdparker** [comment]
Yes, OpenGL 3+ has several cases where ARB extensions are simply "reused". This is one of them.

**Comment by brendanzab** [comment]
So if they're reused from the ARB extensions, would they still be fine to use with the Core Profile?

**Comment by mdparker** [comment]
Yes, they are a part of the core profile from OpenGL 3.0+ and available in prior versions only as an extension. "reuse" just means the specification for the extension (or, at any rate, the interface) wasn't changed when it was adopted as part of the standard -- same function names and parameter lists. In the past, ARB extensions always had an ARB suffix on function names and types, so the names would change when the extension became part of the standard.
