### ISSUE TITLE
ASSIMP: aiMesh structure

### ISSUE THREAD

**Issue by karhu** [mdparker/Derelict3#32]
I recently ran into a problem when using the derelict assimp bindings. 

More specifically, when accessing the mFaces member of an aiMesh instance, mFaces was always "null", which it should never be according to the assimp documentation.

I traced the problem back to the following fact:

in assimp/mesh.h I have:

```
define AI_MAX_NUMBER_OF_COLOR_SETS 0x8
define AI_MAX_NUMBER_OF_TEXTURECOORDS 0x8
```

while in derelict/assimp/types.d I have:

```
const uint AI_MAX_NUMBER_OF_COLOR_SETS = 0x4;
const uint AI_MAX_NUMBER_OF_TEXTURECOORDS = 0x4;
```

This results in a different memory layout of the c and d structs, and aiMesh.mFaces accessing the wrong memory.

**Comment by svenstaro** [comment]
Mh I wonder how I could have messed _that_ up. Anyway, why not fix it and submit a pull request?

**Comment by karhu** [comment]
I don't really have any experience with git nor github, but I'll give it a try :)

**Comment by karhu** [comment]
Ok I just realised that the problem lies with me, as I was using Assimp3 (and not Assimp2) c-header files. 

Assimp3 increases these numbers from 4 to 8. 

Sorry for the inconvenience, feel free to close this issue.

**Comment by svenstaro** [comment]
But the bindings are against assimp 3.

**Comment by karhu** [comment]
Ah even better. Well then back to my git crash course.
