### ISSUE TITLE
FreeImageIO struct small fix

### ISSUE THREAD

**Issue by ancienttoast** [mdparker/Derelict3#37]
alias extern(C) nothrow int function(fi_handle handle, long offset, int origin) FI_SeekProc;

should be

alias extern(C) nothrow int function(fi_handle handle, c_long offset, int origin) FI_SeekProc;

Also, every function pointer in the FreeImageIO struct should be extern(Windows) instead of extern(C) becouse according to the FreeImage documentation they use the stdcall calling convention.

**Comment by mdparker** [comment]
Thanks! Found a couple more instances where c_long/ulong were appropriate. And the function pointers in FreeImageIO are now extern(System).
