### ISSUE TITLE
GLFWscrollfun uses int instead of double

### ISSUE THREAD

**Issue by KoltesDigital** [mdparker/Derelict3#49]
As I updated my repository, the scroll callback of my project didn't work anymore. The scrollback arguments have been changed to double, but Derelict still uses int.

https://github.com/elmindreda/glfw/blob/master/include/GL/glfw3.h#L479

No need to fork for that :) please change the line 299 of glfw/types.d to

```
alias void function(GLFWwindow, double, double) GLFWscrollfun;
```

This change made my project stable again.

Cheers

**Comment by mdparker** [comment]
I'd overlooked that one. Thanks.
