### ISSUE TITLE
How build with another compiler than rdmd ?

### ISSUE THREAD

**Issue by bioinfornatics** [mdparker/Derelict3#5]
Dear,
I would like to know how build with ldc2 ?

**Comment by mdparker** [comment]
It's just a matter of adding a version block to the build script with the appropriate compiler options. Take a look at build/derelict.d, starting from [line 27](https://github.com/aldacron/Derelict3/blob/master/build/derelict.d#L27).

**Comment by bioinfornatics** [comment]
it is exactlyt same as digital mars section. Just instead dmd put ldc2 fot the command line

**Comment by mdparker** [comment]
OK. But what's the version identifier? As soon as I know that I can update the build script.

**Comment by mdparker** [comment]
Ah, I see there's a version(LDC). But, is there a version(LDC2)?

**Comment by mdparker** [comment]
OK. I've implemented it. Please let me know if it works.

**Comment by bioinfornatics** [comment]
ok it work, just i missed -inline do not exist in ldc it is -enable-inlining

**Comment by mdparker** [comment]
Thanks. I've updated the build script.
