### ISSUE TITLE
"Error: struct derelict.sfml2.graphicstypes.sfRenderWindow unknown size"

### ISSUE THREAD

**Issue by vittorioromeo** [mdparker/Derelict3#57]
``` d
module main;

import std.stdio;
import derelict.sfml2.system;
import derelict.sfml2.window;
import derelict.sfml2.graphics;
import derelict.sfml2.audio;

void main(string[] args)
{
    DerelictSFML2Window.load();
    DerelictSFML2System.load();
    DerelictSFML2Graphics.load();
    DerelictSFML2Audio.load();

    sfRenderWindow w;
}
```

Doesn't build. Using MonoDevelop. I have the csfml DLL files in the project folder, I linked all Derelict lib files.

What am I doing wrong?

**Comment by mdparker** [comment]
sfRenderWindow is an opaque type, meaning you can't create instances of it on the stack as you have here. You can only use pointers and cannot allocate them yourself. The only way to get an instance is through a pointer returned by sfRenderWindow_create:

sfRenderWindow\* w = sfRenderWindow_create(...);

You'll find this to be true for many types in the CSFML API.
