### ISSUE TITLE
glfw3 constants mismatch 

### ISSUE THREAD

**Issue by Dav1dde** [mdparker/Derelict3#58]
It seems like GLFW constants as defined by Derelict don't match the GLFW Headers:

[https://github.com/elmindreda/glfw/blob/master/include/GL/glfw3.h#L407](https://github.com/elmindreda/glfw/blob/master/include/GL/glfw3.h#L407) vs. [https://github.com/aldacron/Derelict3/blob/master/import/derelict/glfw3/types.d#L217](https://github.com/aldacron/Derelict3/blob/master/import/derelict/glfw3/types.d#L217)

E.g.:

```
#define GLFW_RESIZABLE            0x00022007
```

and 

```
GLFW_WINDOW_RESIZABLE     = 0x0002100D,
```

**Comment by mdparker** [comment]
Looks like I'm going to have to go through and see what else is no longer up to date. I'll be happy when they finally get into a more stable beta phase.

**Comment by mdparker** [comment]
I think I've got it all. I'll give it a run in a bit to make sure. Thanks for letting me know.
