### ISSUE TITLE
DerelictSFML2Graphics.load() loads missing function.

### ISSUE THREAD

**Issue by Nekroze** [mdparker/Derelict3#62]
Sorry for lack of form this is my first time doing anything like this, anyways onto it.

I have been trying to piece together how to use SFML2 with Derelict3 and i have managed to recompile the latest CSFML2 build and it worked fine until i ran DerelictSFML2Graphics.load() at which point there was an error because derelict/sfml2/graphics.d try's to import the function "sfShader_unbind" which appears to be missing from the current CSFML2 build, by commenting this out it all seems to work fine now. I will continue working with it and report further in case there is still a problem.

I am not sure if this function is meant to be there but was just overlooked in the current CSFML2 build, i cannot seem to get onto their forums to ask.

**Comment by Nekroze** [comment]
After loading the rest of the SFML libraries i have found the same problem for sfFtpListingResponse_getFilename from network.d once again i simply comment out its binding and it worked.

**Comment by mdparker** [comment]
Looking at the CSFML git, I see that sfShader_unbind was removed from the API and sfFtpListingResponse_getFilename was renamed. Thanks for reporting this and I apologize for being so late with my response. I'll update the master with the changes ASAP.
