### ISSUE TITLE
errors compiling with dmd 2.061 (alpha)

### ISSUE THREAD

**Issue by jordisayol** [mdparker/Derelict3#64]
$ dmd -c -op derelict/lua/macros.d

```
derelict/lua/macros.d(128): Error: cannot implicitly convert expression ((*luaL_checkinteger)(L, n)) of type long to int
derelict/lua/macros.d(131): Error: cannot implicitly convert expression ((*luaL_optinteger)(L, n, d)) of type long to int
```

Why build/build.d do not warn these errors?

**Comment by mdparker** [comment]
I have no idea why build.d doesn't give you the errors. But I'm really not interested in problems with alpha versions of DMD. My only concern is the latest release. If this arises as a problem when 2.061 is release, I'll deal with it then.

**Comment by jordisayol** [comment]
Sorry, 'build.d' really warns these errors.

**Comment by ghost** [comment]
It fails for the same reason in 2.060 on platforms where ptrdiff_t is 8 bytes (typedef ptrdiff_t lua_Integer).

**Comment by mdparker** [comment]
OK, I'll look into this.

**Comment by jordisayol** [comment]
errors when compiling to 32-bit differs from 64-bit.
$ dmd -m32 -c -op derelict/lua/functions.d

```
derelict/lua/types.d(58): Error: struct derelict.lua.types.lua_State unknown size
derelict/lua/types.d(58): Error: struct derelict.lua.types.lua_State no size yet for forward reference
```

**Comment by rikkimax** [comment]
I had a play with a version of dmd Walter Bright put on the forums http://forum.dlang.org/thread/507B18AF.1060602@digitalmars.com?page=1 it did compile without errors.
Jordisayol did you compile dmd yourself?

**Comment by jordisayol** [comment]
No, I used the Walter's alpha zip packages, and I still get those errors with the last one (November, 14th)

**Comment by mdparker** [comment]
Sorry, this slipped off my radar. I think I've solved the original issue. If you do a fresh pull it should compile now with 64-bit. I have no way to test it, so I'll wait for you to let me know before closing the issue.

I'm afraid I don't know what to do about the forward reference problem. I don't understand why that is happening, unless it's a bug with the compiler.

**Comment by jordisayol** [comment]
Error solved for 64-bit. Forward reference still present for 32-bit.

Many thanks!

**Comment by mdparker** [comment]
Good. I'll go ahead and close the issue. You can open a new issue about the forward reference if you'd like, but I'm fairly sure this is going to be a dmd bug. And I just realized this is Win64 and not posix, so I'll play around with it on my system later today,
