### ISSUE TITLE
Internal function loading syntax

### ISSUE THREAD

**Issue by weltensturm** [mdparker/Derelict3#65]
Just a suggestion, with mixins function loading could look like this:

```
bindFunctions(
    "FT_Init_FreeType",
    "FT_Done_FreeType",
    "FT_New_Face",
    ...
);
```

**Comment by mdparker** [comment]
We actually use mixins in Derelict 2 in order to support both D1 & D2 in the same codebase. That experience led me to be cautious of using them. Too many mixins can have a visible impact on compile times. So I now only use them if there is a significant benefit. In this case, I don't see one.
