### ISSUE TITLE
void glfwSetWindowPos( int x, int y ) not available in Derelict 3

### ISSUE THREAD

**Issue by MartinMajewski** [mdparker/Derelict3#70]
GLFW's "void glfwSetWindowPos( int x, int y )" function is missing, please add this into the project.

Hmm... found this at the glfw repository:

Removed glfwSetWindowPos and glfwGetWindowPos
glfwGetWindowPos is superseded by glfwGetWindowParam()
with GLFW_POSITION_X and GLFW_POSITION_Y as parameters.

glfwSetWindowPos can easily lead to bad practices
(moving windows around without the users consent), and
has been replaced with the GLFW_POSITION_X/Y window
hints that allow setting the window position for a
newly created window.

---

If this is the current state of glfw, than excuse my issue-report, please! Had an old glfw revision installed!

**Comment by mdparker** [comment]
Yes, AFAIK we're currently up to date with glfw3. The API is certainly a moving target, though, so it's likely to change again at some point.
