### ISSUE TITLE
Awesomium bindings

### ISSUE THREAD

**Issue by Dav1dde** [mdparker/Derelict3#81]
What do you think of adding [awesomium](http://awesomium.com/) 1.6.5 (this version has a c-api) bindings to Derelict?

I already have C-Bindings made: [https://github.com/D-Programming-Deimos/awesomium](https://github.com/D-Programming-Deimos/awesomium)

**Comment by mdparker** [comment]
Thinking about it.

**Comment by mdparker** [comment]
I think I'm going to give this a pass for now.

**Comment by Dav1dde** [comment]
Good to hear, but you maybe want to wait a bit, awesomium 1.7 is released soon (RCs already exist for Windows)

**Comment by mdparker** [comment]
I mean I'm going to pass on this. Not implement it. I may in the future, but definitely not until I decide what to do about DUB.
