### ISSUE TITLE
GLFW3 out of date

### ISSUE THREAD

**Issue by SerialVelocity** [mdparker/Derelict3#82]
Hey,

Can you provide a git revision that the current state of your binding works with? I can then work on a patch to update your bindings to the latest version if you want.

**Comment by mdparker** [comment]
I have no idea. The glfw header is small enough it's easy to update. I'll look in to it in a few hours when I get home from work.

**Comment by mdparker** [comment]
Just updated with the appropriate changes. I can verify that it compiles, loads the dll, and can create and destroy a window. Please let me know if you notice anything wonky. And be aware that the API has had some massive changes, so if you aren't aware of them already I suggest you keep the C header open and use as a reference when updating your code.
