### ISSUE TITLE
Derelict.freetype library names

### ISSUE THREAD

**Issue by rednuck** [mdparker/Derelict3#9]
Not sure the proper way of sending these fixes in so I will send in an issue. 

In derelict.freetype.ft.d the libraries are listed as so:

`else static if(Derelict_OS_Mac)
                      enum libNames = "libfreetype.so.6,libfreetype.so";
    else static if(Derelict_OS_Posix)
                      enum libNames =                        "libfreetype.dylib,libfreetype.6.dylib,libfreetype.6.3.16.dylib,/usr/X11/lib/libfreetype.dylib,/usr/X11/lib/libfreetype.6.dylib,/usr/X11/lib/libfreetype.6.3.16.dylib";`

Should the libnames be switched so the .dylib's are associated with Derelict_OS_Mac and the .so's with Derelict_OS_Posix?

**Comment by mdparker** [comment]
Indeed.
