### ISSUE TITLE
No DUB package yet

### ISSUE THREAD

**Issue by BitPuffin** [mdparker/Derelict3#96]
Come on aldacron, you even covered DUB on the dblog :)

**Comment by mdparker** [comment]
I'll get to it when I can. It's not the most pressing issue for me at the moment.

**Comment by mdparker** [comment]
Going to close this since you've already put up a pull request. Not sure what I'm going to do about that yet, though. Thanks!

**Comment by BitPuffin** [comment]
one thing you could do is to have configurations in the "manifest". So you could do dub build --config=glfw3

**Comment by mdparker** [comment]
Yuck. At this point, I'm leaning toward the monolithic library just for DUB builds, I just want to give it time for any drawbacks I may be missing to percolate through my head.

**Comment by BitPuffin** [comment]
Yeah it seems like that would be the ideal for DUB. As I said, I _think_ it only links to what you use in your code anyways, but I don't know for sure. I might be totally wrong

**Comment by mdparker** [comment]
Well, that's what linkers generally do. Anything you don't use isn't linked in. I'm not worried about that. What I'm concerned about is consistency. When I get to the documentation, or when tutorials start popping up, we'll have a situation where we have to say, "If you've built Derelict with DUB, just link to Derelict3.lib, but if you've used build.d, link with DerelictUtil.lib and DerelictSDL2.lib". Plus, consider independent bindings using DerelictUtil for loading. As a DUB dependency, users will wind up with all of Derelict when they only want the one package. I realize that's the case now when using git directly, but with a package tool like DUB it should be possible to pull down only DerelictUtil if that's all you need. Back when DSSS was still active, that's exactly how it worked and it was great ("dsss net install DerelictUtil DerelictSDL" or something like that).

Alternatively, I could restructure everything... pull DerelictUtil out into a separate repository and reorganize the packages into new repos based around functionality or some such. That's a strong possibility iff DUB becomes so ubiquitous that people expect support for it. But until that day, it's not something I'm inclined to do.
