### ISSUE TITLE
GLFW3 Bindings out of date?

### ISSUE THREAD

**Issue by BitPuffin** [mdparker/Derelict3#99]
Seems like the GLFW3 bindings are dated. glfwWindowShouldClose is undefined. And I suppose there are other functions missing too. But I can't verify that.

**Comment by mdparker** [comment]
That's to be expected. GLFW3 is a moving target and the binding frequently falls behind. I'll look into it when I can.

**Comment by BitPuffin** [comment]
Well of course it's expected :) Just wanted to give a heads up!

**Comment by BitPuffin** [comment]
also missing GLFW_SAMPLES and GLFW_POSITION_X+Y

**Comment by BitPuffin** [comment]
Actually GLFW_POSITION_\* has been removed, my bad

**Comment by mdparker** [comment]
This should be (mostly) fixed. I'll verify as soon as I can.
